# Generated by Django 5.1.1 on 2024-09-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmation', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parking_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_parking_time', models.IntegerField()),
                ('parking_type', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('user_end', models.DateTimeField(blank=True, null=True)),
                ('owner_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Parking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_time', models.DateTimeField()),
                ('is_parking_available', models.BooleanField(default=True)),
                ('cancel', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Reserve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('pick_up_area', models.CharField(max_length=255)),
                ('drop_off', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('user_end', models.DateTimeField(blank=True, null=True)),
                ('owner_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Trip',
                'managed': False,
            },
        ),
    ]
