# Generated by Django 5.1.1 on 2024-09-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Garage",
            fields=[
                ("garageid", models.AutoField(primary_key=True, serialize=False)),
                ("slots", models.IntegerField()),
                ("cctv", models.BooleanField(default=False)),
                ("watchmen", models.BooleanField(default=False)),
                ("area", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Garage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userid", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("phoneno", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("nid", models.IntegerField()),
                ("isowner", models.BooleanField(default=False)),
                ("dob", models.DateField()),
            ],
            options={
                "db_table": "User",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("licensenumber", models.AutoField(primary_key=True, serialize=False)),
                ("modelname", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("seatcapacity", models.IntegerField()),
                ("modelyear", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("ispremium", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "Vehicle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "ownerid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="rental.user",
                    ),
                ),
                ("noofcars", models.IntegerField(blank=True, null=True)),
                ("noofgarages", models.IntegerField(blank=True, null=True)),
                ("verification", models.BooleanField(null=True)),
            ],
            options={
                "db_table": "Owner",
                "managed": False,
            },
        ),
    ]
